name: "api: pr to master"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'api/**'

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          path: api
          registry: docker.pkg.github.com
          repository: fuxingloh/smu-goldman-hackathon/api
          tags: latest
          push: false
