name: "api: pr to master"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'api-news/**'

jobs:
  ci_build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          path: api-news
          registry: docker.pkg.github.com
          repository: fuxingloh/smu-goldman-hackathon/api-news
          tags: latest
          push: false
