name: "api-data: pr to master"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'api-data/**'

jobs:
  build-api-data:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - name: Docker build api-data
        id: api-data
        working-directory: api-data
        run: |
          ./gradlew bootBuildImage
