name: "terraform fmt -check"

on:
  push:
    paths:
      - 'terraform/**'

defaults:
  run:
    working-directory: terraform

jobs:
  fmt:
    name: "fmt -check"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
