name: "web-app: pr to master"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'web-app/**'

jobs:
  ci_build_generate:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - run: yarn install
        working-directory: web-app

      - run: yarn build
        working-directory: web-app

      - run: yarn generate
        working-directory: web-app
